#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/burgertop/burgertop /usr/bin/burgertop

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/burgertop.service ]; then
			rm /etc/systemd/system/burgertop.service /usr/lib/systemd/system/burgertop.service /usr/lib/systemd/user/burgertop.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/burgertop/files/systemd/burgertop.service /usr/lib/systemd/system/burgertop.service
		# try fix error in Ubuntu 18.04
		# Failed to reload burgertop.service: Unit burgertop.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/burgertop.service:10: Executable path is not absolute: pkill -f "burgertop --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/burgertop.service
		fi
		systemctl daemon-reload
		systemctl enable burgertop
		systemctl start burgertop
	fi
fi
