#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/burgertop

		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop burgertop || true
			systemctl disable burgertop || true
			rm /etc/systemd/system/burgertop.service /usr/lib/systemd/system/burgertop.service || true

			serverUser=$(ps -ef | grep -E 'burgertop +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop burgertop >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/burgertop.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
